package langModel;

import myLangModel.NgramUtils;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.assertEquals;


/**
 * This JUnit Test Class has been generated by right clicking on the MiscUtils class
 * and selecting "New" then "Junit Test Case". After that, you have to select the methods
 * for which you would like to generate tests.
 * In practice, you will duplicate manually the test methods to possibly create
 * several tests for one method.
 *
 * Your work is then to remove the fail parts and to implement each test.
 * One method is given as an example
 *
 * To run them:
 * either right click on the class name or simply on the method name and
 * select "Run As Junit Test".
 *
 * Class NgramUtilsTest: JUnit Test class to test the class NgramUtils.
 *
 * @author N. Hernandez and S. Quiniou (2015)
 *
 */
public class NgramUtilsTest {

    String sentence = "<s> cette phrase est de taille 9 . </s>";
    String ngram = "où commence l' historique de ce n-gramme";


	/*@Before
	public void initialize () {
		System.out.printf("Set ngram>%s<\n",ngram);
		System.out.printf("Set sentence>%s<\n",sentence);
	}*/


    /**
     * Test method for {@link NgramUtils#getSequenceSize(String)}.
     */
    @Test
    public void testGetSequenceSize() {
        // DONE
        assertEquals(9, NgramUtils.getSequenceSize(sentence));


    }


    /**
     * Test method for {@link NgramUtils#generateNgrams(String, int, int)}.
     */
    @Test
    public void testGenerateNgramsBigrams() {
        // DONE
        System.out.println(NgramUtils.generateNgrams(sentence,1,2));
        List<String> list = new ArrayList<>();
        list.addAll(Arrays.asList("<s>", "cette", "phrase", "est", "de", "taille", "9", ".", "</s>", "<s> cette", "cette phrase", "phrase est", "est de", "de taille", "taille 9", "9 .",". </s>"));
        assertEquals(NgramUtils.generateNgrams(sentence,1,2),list);


    }


    /**
     * Test method for {@link NgramUtils#generateNgrams(String, int, int)}.
     */
    @Test
    public void testGenerateNgrams1to3grams() {
        // DONE
        System.out.println(NgramUtils.generateNgrams(sentence, 1,3));
        List<String> list = new ArrayList<>();
        list.addAll(Arrays.asList("<s>", "cette", "phrase", "est", "de", "taille", "9", ".", "</s>", "<s> cette", "cette phrase", "phrase est", "est de", "de taille", "taille 9", "9 .", ". </s>", "<s> cette phrase", "cette phrase est", "phrase est de", "est de taille", "de taille 9", "taille 9 .", "9 . </s>"));
        assertEquals(NgramUtils.generateNgrams(sentence,1,3), list);
    }


    /**
     * Test method for {@link NgramUtils#getHistory(String, int)}.
     */
    @Test
    public void testGetHistoryOrder2() {
        // DONE
        System.out.println(NgramUtils.getHistory(ngram, 2));
        String string = "ce";
        assertEquals(NgramUtils.getHistory(ngram,2), string);

    }


    /**
     * Test method for {@link NgramUtils#getHistory(String, int)}.
     */
    @Test
    public void testGetHistoryOrder3() {
        // DONE
        System.out.println(NgramUtils.getHistory(ngram, 3));
        String string = "de ce";
        assertEquals(NgramUtils.getHistory(ngram,3), string);
    }

    /**
     * Test method for {@link NgramUtils#getHistory(String, int)}.
     */
    @Test
    public void testGetHistoryOrder0() {
        // DONE
        System.out.println(NgramUtils.getHistory(ngram, 0));
        String string = "";
        assertEquals(NgramUtils.getHistory(ngram,0), string);

    }


    /**
     * Test method for {@link NgramUtils#decomposeIntoNgrams(String, int)}.
     */
    @Test
    public void testDecomposeInto1grams() {
        // DONE
        System.out.println(NgramUtils.decomposeIntoNgrams(sentence, 1));
        List<String> list = new ArrayList<>();
        list.addAll(Arrays.asList("<s>", "cette", "phrase", "est", "de", "taille", "9", ".", "</s>"));
        assertEquals(NgramUtils.decomposeIntoNgrams(sentence, 1), list);
    }


    /**
     * Test method for {@link NgramUtils#decomposeIntoNgrams(String, int)}.
     */
    @Test
    public void testDecomposeInto2grams() {
        // DONE
        System.out.println(NgramUtils.decomposeIntoNgrams(sentence, 2));
        List<String> list = new ArrayList<>();
        list.addAll(Arrays.asList("<s>", "<s> cette", "cette phrase", "phrase est", "est de", "de taille", "taille 9", "9 .", ". </s>"));
        assertEquals(NgramUtils.decomposeIntoNgrams(sentence, 2), list);

    }


    /**
     * Test method for {@link NgramUtils#decomposeIntoNgrams(String, int)}.
     */
    @Test
    public void testDecomposeInto3grams() {
        // TODO
        System.out.println(NgramUtils.decomposeIntoNgrams(sentence, 3));
        List<String> list = new ArrayList<>();
        list.addAll(Arrays.asList("<s>", "<s> cette", "<s> cette phrase", "cette phrase est", "phrase est de", "est de taille", "de taille 9", "taille 9 .", "9 . </s>"));
        assertEquals(NgramUtils.decomposeIntoNgrams(sentence, 3), list);


    }


    /**
     * Test method for {@link NgramUtils#word2characterTokens(String)}.
     */
    @Test
    public void testWord2characterTokens() {
        // TODO
        String word = "phrase";
        System.out.println(NgramUtils.word2characterTokens(word));
        assertEquals(NgramUtils.word2characterTokens(word), "p h r a s e");
    }



    @Rule
    public TestName name = new TestName();

    @Before
    public void printSeparator()
    {
        System.out.println("\n=== " + name.getMethodName() + " =====================");
    }
}
